ALTER DATABASE [Patients] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
RESTORE DATABASE [Patients] 
 FROM DISK = N'C:/_BISolutions/Databases/Patients.bak' 
 WITH RECOVERY, REPLACE;
ALTER DATABASE [Patients] SET MULTI_USER;

ALTER DATABASE [DoctorsSchedules] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
RESTORE DATABASE [DoctorsSchedules] 
 FROM DISK = N'C:/_BISolutions/Databases/DoctorsSchedules.bak' 
 WITH RECOVERY, REPLACE;
ALTER DATABASE [Patients] SET MULTI_USER;


